apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  - ReadOnlyMany
  nfs:
    path: /srv/nfs_registry
    server: 192.168.99.106
  persistentVolumeReclaimPolicy: Retain
